### ISSUE TITLE
Kako pogosto se posodobijo CSV datoteke na Githubu?

### ISSUE THREAD

**Issue by MatejKovacic** [slo-covid-19/data#1]
Smiselno bi bilo, da se posodobijo samodejno večkrat na dan, da so sinhronizirane z Google Docsom.

Drugače pa hvala za ta projekt. Vaše podatke uporabljamo na https://ustavimokorono.si/.

**Comment by MatejKovacic** [comment]
Pa še eno vprašanje... a struktura podatkov je zdaj fiksna? Ker danes se je že nekajkrat spremenila.

**Comment by overlordtm** [comment]
Glede frekvence, vsaj 1 export na dan se naredi, ponavadi ga @lukarenko se rocno sprozi enkrat po 14h. Tako da v praksi se vsaj ene 5x na dan exporta.

Glede strukture, na zacetku smo se se zelo lovili, sedaj ima vsaj stats.csv statistika fiksne stolpce (`cum` smo zamenjlai z `todate`). Je pa tako da se doloceni stolcpi dodajajo po potrebi (nove bolnisnice), starih pa nimamo namena vec spreminjat (vsaj upam da je tako)

**Comment by lukarenko** [comment]
Bi samo dodal: export poženemo, ko so podatki v nekem konsistentnem stanju, primeri:
- imamo vse podatke o testih
- imamo vse podatke o bolnišnicah
- imamo vse podatke po krajih (za katere rabimo več časa, ker rabimo OCR)
Kdaj se požene dodatno, ko recimo izboljšamo/popravimo model za bolnišnično obravnavo.
Imena polj pa smo popravili, zato da so bolj jasna in se bomo trudili, da jih ne podremo.
Če hočete biti redno obveščeni vas lahko povabimo v našo Slack skupino (pošlji me e-mail na DM ali mail)
